version: "3"

services:
    php:
        build: ./docker/php
        environment:
            XDEBUG_CONFIG: '${XDEBUG_CONFIG}'
        expose:
            - '9000'
        volumes:
            - '~/.cache/composer:/tmp/cache'
            - './webapp:/var/www/html'
        depends_on:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ltymub
            MYSQL_USER: developer
            MYSQL_PASSWORD: 123456
        volumes:
            - "./var/db:/var/lib/mysql"
        ports:
            - "3306:3306"
    nginx:
        build: ./docker/nginx
        ports:
            - "8000:80"
        volumes:
            - './etc/nginx:/etc/nginx/conf.d'
            - './webapp:/var/www/html'
        depends_on:
            - php
